Initial commit for problem 11-1
SVizor42/made_2019_algo pull request #10
Opened 2019-12-13 12:49 UTC by SVizor42

Прошу проверить задачу.
ContestName: Timur Kamaliev
Группа MADE-12
Submissions for problem 11_1
https://contest.yandex.ru/contest/16167/run-report/28846549/

2019-12-24 04:40 UTC, ylyubimov requested changes

2019-12-24 04:40 UTC, ylyubimov commented on assignment_6/11_1/main.cpp
> +    std::vector< std::vector<size_t> > graph(v);
В следующих задачах хотелось бы, чтобы граф был структурой данных

2019-12-24 04:40 UTC, ylyubimov commented on assignment_6/11_1/main.cpp
> +        bool flag = 0;
bool инициализируй bool'ами, а не int'aми

2019-12-24 04:40 UTC, ylyubimov commented on assignment_6/11_1/main.cpp
> +        bool flag = 0;
Ну и название флагу было бы неплохо дать более адекватно или комментарий

2019-12-24 05:53 UTC, SVizor42 commented on assignment_6/11_1/main.cpp
> +        bool flag = 0;
Done.

2019-12-24 05:55 UTC, SVizor42 commented on assignment_6/11_1/main.cpp
> +    std::vector< std::vector<size_t> > graph(v);
Допустимо ли задавать алиас через using? Внес правки в код. Просто во всех последующих решениях использовал такой подход.

2019-12-30 13:15 UTC, ylyubimov approved these changes

2019-12-30 13:47 UTC, merged