Fixies in 2_2 problem.
SVizor42/made_2019_algo pull request #2
Opened 2019-11-09 19:45 UTC by SVizor42

Яков,
реализовал кучу, прошу проверить.
=======================================================
Привет,

Это классно, что ты знаешь как сделать кучу из вектора в std. Но задание было в том, чтобы ты написал свою. И понял, как она работает изнутри
Реализуй кучу сам и пришли мне Pull request на GitHub, пожалуйста.

Яков.

2019-11-12 07:14 UTC, ylyubimov requested changes
Я помню, что я тебя уже видел.
Но было бы классно здесь указать свою ФИО, а также дать ссылку на контест.
Потому что по почте я буду долго искать

2019-11-12 07:14 UTC, ylyubimov commented on assignment_1/2_2/main.cpp
> +	void SiftUp(int node);
Кажется, публичными должны быть только методы
Add и getMin?
Почему у тебя какие-то методы называются с большой буквы, какие-то с маленькой. Каким code-style'ом ты пользуешься?

2019-11-12 07:14 UTC, ylyubimov commented on assignment_1/2_2/main.cpp
> +	int size();
Метод не меняет состояние объекта => const

2019-11-12 07:14 UTC, ylyubimov commented on assignment_1/2_2/main.cpp
> +	int getLeftChild(int node);
Эти методы вообще не используют от объекта ничего => static
или вообще в анонимном namespace'е в не класса

2019-11-12 07:14 UTC, ylyubimov commented on assignment_1/2_2/main.cpp
> +		heap.Add(number);
Сможешь считать массив и построить кучу за O(n) через конструктор?

2019-11-12 08:27 UTC, SVizor42 commented on assignment_1/2_2/main.cpp
> +	int size();
Добавил.

2019-11-12 08:28 UTC, SVizor42 commented on assignment_1/2_2/main.cpp
> +	int getLeftChild(int node);
Добавил.

2019-11-12 08:29 UTC, SVizor42 commented on assignment_1/2_2/main.cpp
> +	void SiftUp(int node);
Поправил. Перенес в приватную область. 
За основу брал:
https://google.github.io/styleguide/cppguide.html

2019-11-12 08:54 UTC, SVizor42 commented on assignment_1/2_2/main.cpp
> +		heap.Add(number);
Добавил новый конструктор.

2019-11-12 08:58 UTC, SVizor42 reviewed
ContestName: Timur Kamaliev
Ссылка на исходную посылку из почтовой переписки:
https://contest.yandex.ru/contest/14907/run-report/23601008/

2019-11-13 21:56 UTC, ylyubimov approved these changes

2019-11-14 03:47 UTC, merged