Problem 6_1
SVizor42/made_2019_algo pull request #6
Opened 2019-11-22 22:03 UTC by SVizor42

Прошу проверить задачу.
ContestName: Timur Kamaliev
Группа MADE-12
Submissions for problem 6_1
https://contest.yandex.ru/contest/15368/run-report/26409623/

2019-11-26 23:59 UTC, ylyubimov requested changes

2019-11-26 23:59 UTC, ylyubimov commented on main.cpp
> +        delete this->left;
Это рекурсивный вызов деструктора. Дерево не сбалансировано рекурсии быть не должно

2019-11-26 23:59 UTC, ylyubimov commented on main.cpp
> +        std::cout << node->value_ << " ";
Фунция должна называться PreOrder и получать функтор параметром.
Ввод/вывод у нас возможен только в main'е

2019-11-26 23:59 UTC, ylyubimov commented on main.cpp
> +    ~Tree();
Правило 5ти

2019-11-26 23:59 UTC, ylyubimov commented on main.cpp
> +struct treeNode {
Пусть будет приватной структурой дерева

2019-11-26 23:59 UTC, ylyubimov commented on main.cpp
> +        std::cout << node->value_ << " ";
Кстати через нее же можно реализовать и деструктор, если подумать

2019-11-28 00:52 UTC, SVizor42 commented on main.cpp
> +    ~Tree();
Поправил. Да, Степан упоминал об этом на записи семинара по хэш-таблицам.

2019-11-28 00:54 UTC, SVizor42 commented on main.cpp
> +        std::cout << node->value_ << " ";
Реализовал через передачу функтора параметром и вывод, и деструктор.

2019-11-28 00:55 UTC, SVizor42 commented on main.cpp
> +        delete this->left;
Переписал деструктор.

2019-11-28 01:02 UTC, SVizor42 commented on main.cpp
> +struct treeNode {
Включил структуру в состав класса дерева, но в публичную часть. Могу перенести в приватную, но тогда не понятно, как передавать лямбду в преордер в мэйне для вывода, т.к. структура станет скрытой деталью реализации.

2019-11-28 01:05 UTC, SVizor42 commented on main.cpp
> +struct treeNode {
Если только создать условный PrintTree в паблике и там делать cout, а структуру и PreOrder перенести в приватную часть.

2019-11-30 13:35 UTC, ylyubimov approved these changes

2019-11-30 22:17 UTC, merged