Problem 8_1
SVizor42/made_2019_algo pull request #8
Opened 2019-11-26 13:22 UTC by SVizor42

Прошу проверить задачу.
ContestName: Timur Kamaliev
Группа MADE-12
Submissions for problem 8_1
https://contest.yandex.ru/contest/15766/run-report/27059475/

2019-12-03 06:49 UTC, ylyubimov requested changes

2019-12-03 06:49 UTC, ylyubimov commented on main.cpp
> +    table[hash] = key;
Вставлять надо в первую deleted позицию. Что будет, если пустых ячеек нет, а есть только deleted?

2019-12-03 06:49 UTC, ylyubimov commented on main.cpp
> +    table_size++;
Ты стабильно увеличиваешь table_size, но нигде не уменьшаешь
Добавляя/удаляя один элемент, я могу раздуть хеш-таблицу

2019-12-03 06:49 UTC, ylyubimov commented on main.cpp
> +class HashTable {
Давай сделаем шаблон
template <class T, class THash>

2019-12-03 06:49 UTC, ylyubimov commented on main.cpp
> +    while (table[hash] != "" && table[hash] != "Deleted") {
Пустое значение и значение "удалено" можно задавать в конструкторе. А то, я не смогу положить туда значения "Deleted"

2019-12-06 08:32 UTC, SVizor42 commented on main.cpp
> +class HashTable {
Переделал под шаблонный класс.

2019-12-06 08:33 UTC, SVizor42 commented on main.cpp
> +    while (table[hash] != "" && table[hash] != "Deleted") {
Теперь пустое и удаленное значения можно задавать в конструкторе.

2019-12-06 08:39 UTC, SVizor42 commented on main.cpp
> +    table[hash] = key;
Будет вызван Rehash при заполненности текущей таблицы на 3/4. Но в целом согласен, не оптимально. Поправил.

2019-12-06 08:40 UTC, SVizor42 commented on main.cpp
> +    table_size++;
Добавил уменьшение размера при удалении элемента.

2019-12-06 08:41 UTC, SVizor42 reviewed
After review changes

2019-12-08 10:20 UTC, ylyubimov requested changes

2019-12-08 10:20 UTC, ylyubimov commented on main.cpp
> +    while (table[hash] != empty && table[hash] != deleted) {
Теперь ты вставишь в deleted ячейку, но могут появится дубликаты

2019-12-09 14:16 UTC, SVizor42 commented on main.cpp
> +    while (table[hash] != empty && table[hash] != deleted) {
Немного переписал метод. Но тест, на котором ломается, так и не подобрал.
Если есть контр-пример, прошу отписать.

2019-12-11 07:35 UTC, ylyubimov requested changes

2019-12-11 07:35 UTC, ylyubimov commented on main.cpp
> +        if (table[hash] == key) {
а если она deleted?

2019-12-11 07:35 UTC, ylyubimov commented on main.cpp
> +                table[hash] = key;
Так дубликаты все равно будут.

2019-12-11 07:35 UTC, ylyubimov commented on main.cpp
> +                table[hash] = key;
Попробуй пример:
Контр пример подобрать очень сложно, потому что он зависит от размера таблицы.
Ну предположим ты можешь сделать "плохую" хеш-функцию всегда возвращающую 0.
Потом положить три разных строки: "A", "B", "C". Потом удалить "B" и снова положить "C"

2019-12-12 12:58 UTC, SVizor42 commented on main.cpp
> +                table[hash] = key;
Ок, кажется понял. Теперь ясно, почему не смог подобрать такой тест, хэш-функция не позволяла. Пришлось принудительно возвращать 0 для тестирования. Спс за пример. 
Сейчас как раз смотрю семинар 6, Степан рассказывает о такой ошибке.
Поправил, должно работать.

2019-12-12 13:06 UTC, SVizor42 commented on main.cpp
> +        if (table[hash] == key) {
Я же в случае удаления записываю в ячейку таблицы значение deleted.
Или имеется в виду, что может придти key == deleted? Добавил проверку ключа. 
Если неправильно понял, поясни, пжлста.

2019-12-24 04:19 UTC, ylyubimov approved these changes

2019-12-24 05:35 UTC, merged